server:
  port: 8080 # Porta interna do contêiner

spring:
  application:
    name: ms-auth

  # Configuração para o MongoDB (para rodar LOCALMENTE, sem Docker)
  data:
    mongodb:
      uri: mongodb://localhost:27017/autenticacao_db 

  # Configurações de E-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET}

# Configuração do RabbitMQ (para rodar LOCALMENTE, sem Docker)
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest