server:
  port: 8080 # Porta interna do contêiner

spring:
  application:
    name: ms-cursos # Nome do microsserviço

  datasource:
    # Aponta para o serviço 'db-cursos' no docker-compose.yml
    url: jdbc:postgresql://db-cursos:5432/elarning_cursos_db 
    username: ${POSTGRES_USER}   # (Vem do .env)
    password: ${POSTGRES_PASSWORD} # (Vem do .env)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' cria/altera as tabelas automaticamente.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect