services:
  gateway-api:
    profiles: ["app"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-api
    env_file: .env
    ports:
      # A porta 8080 do host mapeia para a 8080 interna do Node (definida no server.js)
      - "${GATEWAY_HTTP_PORT:-8080}:8080" 
    networks:
      - elearning-net

networks:
  elearning-net:
    external: true